IF OBJECT_ID('tempdb..#TEMP1') IS NOT NULL
    DROP TABLE #TEMP1

DECLARE @TEXT NVARCHAR(MAX), 
	    @X INT = 1, 
		@COLUNA VARCHAR(MAX), 
		@VLR_COLUNA VARCHAR(MAX),
		@TABELA VARCHAR(MAX) = '',
		@CONDICAO VARCHAR(MAX) = ''

SET @COLUNA = 'PK_COD_ENTIDADE'
SET @VLR_COLUNA = '13029061'

SELECT 
	IDENTITY(INT,1,1) ID,
	COL.name COLUNA,
	OBJ.name TABELA
INTO #TEMP1
FROM SYS.all_columns COL
JOIN SYS.all_objects OBJ ON OBJ.object_id = COL.object_id
WHERE COL.name LIKE '%'+@COLUNA+'%'
AND OBJ.type_desc = 'USER_TABLE'


DECLARE C_TABELA CURSOR FOR
SELECT ID, COLUNA, TABELA FROM #TEMP1

OPEN C_TABELA
FETCH NEXT FROM C_TABELA
INTO @X, @TABELA, @CONDICAO

WHILE @@FETCH_STATUS = 0
BEGIN 
	SET @TABELA = (SELECT TABELA FROM #TEMP1 WHERE ID = @X)
	
	SET @CONDICAO = (SELECT COLUNA FROM #TEMP1 WHERE ID = @X)
	
	--SET @TEXT = 'SELECT ''' + @TABELA + ''' TABELA, * FROM ' + (@TABELA) + ' WHERE ' +  (@CONDICAO) + ' = ' + @VLR_COLUNA

	SET @TEXT = 'DELETE FROM ' + (@TABELA) + ' WHERE ' +  (@CONDICAO) + ' = ' + @VLR_COLUNA
	
	EXEC SP_EXECUTESQL @TEXT
	
	FETCH NEXT FROM C_TABELA
	INTO @X, @TABELA, @CONDICAO
END

CLOSE C_TABELA
DEALLOCATE C_TABELA

IF OBJECT_ID('tempdb..#TEMP1') IS NOT NULL
    DROP TABLE #TEMP1